hardcore_bucket: true

disable_bonemeal: true

chorus_fruit_only_grows_on_end: true
nether_wart_only_grows_on_nether: true

# for materials see: https://papermc.io/javadocs/paper/1.18/org/bukkit/material.html

# <material> <moisture necessary>
# moisture level goes from 0 to 7, being 0 the driest.
blocks_with_minimal_farmland_moisture_to_grow:
   - beetroot 7
   - carrot 7
   - melon_stem 7
   - potato 7
   - pumpkin_stem 7
   - wheat 7

# <material> <sky light necessary>
# skylight goes from 0 to 15, being 0 the darkest.
blocks_with_minimal_skylight_to_grow:
   - bamboo 15
   - bamboo_sapling 15
   - beetroot 15
   - carrot 15
   - melon_stem 15
   - melon 15
   - potato 15
   - pumpkin_stem 15
   - pumpkin 15
   - wheat 15
   - cactus 15
   - sugar_cane 15
   - sweet_berry_bush 15
   - cocoa 8
   - acacia_sapling 15
   - birch_sapling 15
   - dark_oak_sapling 15
   - jungle_sapling 15
   - oak_sapling 15
   - spruce_sapling 15
